// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxsgllrjwhfpfbyeqbmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4c2dsbHJqd2hmcGZieWVxYm1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3NzYyNTYsImV4cCI6MjA3NTM1MjI1Nn0.PNH_tNZe69cniPzmMD5xVAOKUQCiGMgL0nR3d5kH328";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
